version: '3.8'

services:
  manga_vocab_app:
    build:
      context: .  # Указывает на текущую директорию, где находится docker-compose.yml
      dockerfile: .devcontainer/Dockerfile # Указывает на путь к вашему Dockerfile
    container_name: manga_vocab_app
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
